### ISSUE TITLE
DO NOT USE THIS!

### ISSUE THREAD

**Issue by SorinGFS** [rajathavalam/express-mvc-generator#11]
This script tries to replace the default express cli **with its own!**

As it sits, **THIS IS A MALWARE!!!**

**Comment by rajaramtt** [comment]
@SorinGFS it’s not malware, earlier I was modified for the creating folder structure! 

Currently Project is inactive we are not actively updating the project due to some personal work.

**Comment by SorinGFS** [comment]
**Project is NOT INACTIVE, you are lying!** And you didn't make any change since may 2017!
**See line 154**
```bash
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\myUser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'express-mvc-generator',
1 verbose cli   '-g'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose npm-session d558d15c91651fa6
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/express-mvc-generator 943ms
8 http fetch GET 200 https://registry.npmjs.org/express-mvc-generator/-/express-mvc-generator-2.2.4.tgz 1046ms
9 silly pacote tag manifest for express-mvc-generator@latest fetched in 2054ms
10 timing stage:loadCurrentTree Completed in 2076ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule express-mvc-generator@2.2.4 checking installable status
18 http fetch GET 200 https://registry.npmjs.org/sorted-object 34ms
19 http fetch GET 304 https://registry.npmjs.org/mkdirp 81ms (from cache)
20 http fetch GET 304 https://registry.npmjs.org/commander 84ms (from cache)
21 silly pacote range manifest for mkdirp@>0.0.0 fetched in 91ms
22 silly resolveWithNewModule mkdirp@1.0.4 checking installable status
23 http fetch GET 200 https://registry.npmjs.org/sorted-object/-/sorted-object-2.0.1.tgz 62ms
24 silly pacote range manifest for sorted-object@>0.0.0 fetched in 103ms
25 silly resolveWithNewModule sorted-object@2.0.1 checking installable status
26 http fetch GET 200 https://registry.npmjs.org/commander/-/commander-7.2.0.tgz 54ms
27 silly pacote range manifest for commander@>0.0.0 fetched in 152ms
28 silly resolveWithNewModule commander@7.2.0 checking installable status
29 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 161ms
30 timing stage:loadIdealTree Completed in 165ms
31 silly currentTree npm
32 silly idealTree npm
32 silly idealTree `-- express-mvc-generator@2.2.4
32 silly idealTree   +-- commander@7.2.0
32 silly idealTree   +-- mkdirp@1.0.4
32 silly idealTree   `-- sorted-object@2.0.1
33 silly install generateActionsToTake
34 timing stage:generateActionsToTake Completed in 8ms
35 silly diffTrees action count 4
36 silly diffTrees add commander@7.2.0
37 silly diffTrees add mkdirp@1.0.4
38 silly diffTrees add sorted-object@2.0.1
39 silly diffTrees add express-mvc-generator@2.2.4
40 silly decomposeActions action count 32
41 silly decomposeActions fetch commander@7.2.0
42 silly decomposeActions extract commander@7.2.0
43 silly decomposeActions preinstall commander@7.2.0
44 silly decomposeActions build commander@7.2.0
45 silly decomposeActions install commander@7.2.0
46 silly decomposeActions postinstall commander@7.2.0
47 silly decomposeActions finalize commander@7.2.0
48 silly decomposeActions refresh-package-json commander@7.2.0
49 silly decomposeActions fetch mkdirp@1.0.4
50 silly decomposeActions extract mkdirp@1.0.4
51 silly decomposeActions preinstall mkdirp@1.0.4
52 silly decomposeActions build mkdirp@1.0.4
53 silly decomposeActions install mkdirp@1.0.4
54 silly decomposeActions postinstall mkdirp@1.0.4
55 silly decomposeActions finalize mkdirp@1.0.4
56 silly decomposeActions refresh-package-json mkdirp@1.0.4
57 silly decomposeActions fetch sorted-object@2.0.1
58 silly decomposeActions extract sorted-object@2.0.1
59 silly decomposeActions preinstall sorted-object@2.0.1
60 silly decomposeActions build sorted-object@2.0.1
61 silly decomposeActions install sorted-object@2.0.1
62 silly decomposeActions postinstall sorted-object@2.0.1
63 silly decomposeActions finalize sorted-object@2.0.1
64 silly decomposeActions refresh-package-json sorted-object@2.0.1
65 silly decomposeActions fetch express-mvc-generator@2.2.4
66 silly decomposeActions extract express-mvc-generator@2.2.4
67 silly decomposeActions preinstall express-mvc-generator@2.2.4
68 silly decomposeActions build express-mvc-generator@2.2.4
69 silly decomposeActions install express-mvc-generator@2.2.4
70 silly decomposeActions postinstall express-mvc-generator@2.2.4
71 silly decomposeActions finalize express-mvc-generator@2.2.4
72 silly decomposeActions refresh-package-json express-mvc-generator@2.2.4
73 silly install executeActions
74 silly doSerial global-install 32
75 verbose correctMkdir C:\Users\myUser\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
76 verbose makeCacheDir UID & GID are irrelevant on win32
77 verbose lock using C:\Users\myUser\AppData\Roaming\npm-cache\_locks\staging-5762d37cf152ad11.lock for C:\Users\myUser\AppData\Roaming\npm\node_modules\.staging
78 silly doParallel extract 4
79 silly extract commander@7.2.0
80 silly extract mkdirp@1.0.4
81 silly extract sorted-object@2.0.1
82 silly extract express-mvc-generator@2.2.4
83 silly tarball trying commander@>0.0.0 by hash: sha512-QrWXB+ZQSVPmIWIhtEO9H+gwHaMGYiF5ChvoJ+K9ZGHG/sVsa6yiesAD1GC/x46sET00Xlwo1u49RVVVzvcSkw==
84 silly tarball trying mkdirp@>0.0.0 by hash: sha512-vVqVZQyf3WLx2Shd0qJ9xuvqgAyKPLAiqITEtqW0oIUjzo3PePDd6fW9iFz30ef7Ysp/oiWqbhszeGWW2T6Gzw==
85 silly tarball trying express-mvc-generator@latest by hash: sha1-GT+YWvPt2ffn+MC6KsbQtDtDaDA=
86 silly tarball trying sorted-object@>0.0.0 by hash: sha1-fWMfS9OnmKJK8d/8+/6DM3pd9fw=
87 silly extract sorted-object@>0.0.0 extracted to C:\Users\myUser\AppData\Roaming\npm\node_modules\.staging\sorted-object-96a865e2 (41ms)
88 silly extract mkdirp@>0.0.0 extracted to C:\Users\myUser\AppData\Roaming\npm\node_modules\.staging\mkdirp-401661b5 (48ms)
89 silly extract commander@>0.0.0 extracted to C:\Users\myUser\AppData\Roaming\npm\node_modules\.staging\commander-c2123525 (49ms)
90 silly extract express-mvc-generator@latest extracted to C:\Users\myUser\AppData\Roaming\npm\node_modules\.staging\express-mvc-generator-d131f7a8 (66ms)
91 timing action:extract Completed in 69ms
92 silly doReverseSerial unbuild 32
93 silly doSerial remove 32
94 silly doSerial move 32
95 silly doSerial finalize 32
96 silly finalize C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator\node_modules\commander
97 silly finalize C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator\node_modules\mkdirp
98 silly finalize C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator\node_modules\sorted-object
99 silly finalize C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator
100 timing action:finalize Completed in 17ms
101 silly doParallel refresh-package-json 4
102 silly refresh-package-json C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator\node_modules\commander
103 silly refresh-package-json C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator\node_modules\mkdirp
104 silly refresh-package-json C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator\node_modules\sorted-object
105 silly refresh-package-json C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator
106 timing action:refresh-package-json Completed in 40ms
107 silly doParallel preinstall 4
108 silly preinstall commander@7.2.0
109 info lifecycle commander@7.2.0~preinstall: commander@7.2.0
110 silly preinstall mkdirp@1.0.4
111 info lifecycle mkdirp@1.0.4~preinstall: mkdirp@1.0.4
112 silly preinstall sorted-object@2.0.1
113 info lifecycle sorted-object@2.0.1~preinstall: sorted-object@2.0.1
114 silly preinstall express-mvc-generator@2.2.4
115 info lifecycle express-mvc-generator@2.2.4~preinstall: express-mvc-generator@2.2.4
116 timing action:preinstall Completed in 2ms
117 silly doSerial build 32
118 silly build commander@7.2.0
119 info linkStuff commander@7.2.0
120 silly linkStuff commander@7.2.0 has C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator\node_modules as its parent node_modules
121 silly linkStuff commander@7.2.0 is part of a global install
122 silly linkStuff commander@7.2.0 is installed into a global node_modules
123 silly build mkdirp@1.0.4
124 info linkStuff mkdirp@1.0.4
125 silly linkStuff mkdirp@1.0.4 has C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator\node_modules as its parent node_modules
126 silly linkStuff mkdirp@1.0.4 is part of a global install
127 silly linkStuff mkdirp@1.0.4 is installed into a global node_modules
128 verbose linkBins [
128 verbose linkBins   { mkdirp: 'bin/cmd.js' },
128 verbose linkBins   'C:\\Users\\myUser\\AppData\\Roaming\\npm\\node_modules\\express-mvc-generator\\node_modules\\.bin',
128 verbose linkBins   false
128 verbose linkBins ]
129 silly build sorted-object@2.0.1
130 info linkStuff sorted-object@2.0.1
131 silly linkStuff sorted-object@2.0.1 has C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator\node_modules as its parent node_modules
132 silly linkStuff sorted-object@2.0.1 is part of a global install
133 silly linkStuff sorted-object@2.0.1 is installed into a global node_modules
134 silly build express-mvc-generator@2.2.4
135 info linkStuff express-mvc-generator@2.2.4
136 silly linkStuff express-mvc-generator@2.2.4 has C:\Users\myUser\AppData\Roaming\npm\node_modules as its parent node_modules
137 silly linkStuff express-mvc-generator@2.2.4 is part of a global install
138 silly linkStuff express-mvc-generator@2.2.4 is installed into a global node_modules
139 silly linkStuff express-mvc-generator@2.2.4 is installed into the top-level global node_modules
140 verbose linkBins [
140 verbose linkBins   { express: 'bin/express' },
140 verbose linkBins   'C:\\Users\\myUser\\AppData\\Roaming\\npm',
140 verbose linkBins   true
140 verbose linkBins ]
141 timing action:build Completed in 13ms
142 verbose unlock done using C:\Users\myUser\AppData\Roaming\npm-cache\_locks\staging-5762d37cf152ad11.lock for C:\Users\myUser\AppData\Roaming\npm\node_modules\.staging
143 timing stage:rollbackFailedOptional Completed in 34ms
144 timing stage:runTopLevelLifecycles Completed in 2435ms
145 verbose stack Error: EEXIST: file already exists, cmd shim 'C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator\bin\express' -> 'C:\Users\myUser\AppData\Roaming\npm\express'
145 verbose stack     at simulateEEXIST (C:\Users\myUser\AppData\Roaming\npm\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:87:15)
145 verbose stack     at C:\Users\myUser\AppData\Roaming\npm\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:78:17
145 verbose stack     at C:\Users\myUser\AppData\Roaming\npm\node_modules\npm\node_modules\read-cmd-shim\index.js:51:29
145 verbose stack     at C:\Users\myUser\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:123:16
145 verbose stack     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
146 verbose cwd C:\Users\myUser\Documents\Visual Studio Code\Playground\express-mvc
147 verbose Windows_NT 6.3.9600
148 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\myUser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "express-mvc-generator" "-g"
149 verbose node v12.19.0
150 verbose npm  v6.14.8
151 error code EEXIST
152 error path C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator\bin\express
153 error dest C:\Users\myUser\AppData\Roaming\npm\express
154 error EEXIST: file already exists, cmd shim 'C:\Users\myUser\AppData\Roaming\npm\node_modules\express-mvc-generator\bin\express' -> 'C:\Users\myUser\AppData\Roaming\npm\express'
155 error File exists: C:\Users\myUser\AppData\Roaming\npm\express
156 error Remove the existing file and try again, or run npm
157 error with --force to overwrite files recklessly.
158 verbose exit [ 1, true ]
```

**Comment by rajaramtt** [comment]
@SorinGFS 


![image](https://user-images.githubusercontent.com/17231665/114682089-672c2400-9d2c-11eb-8929-dc2ffd1cadca.png)


If you feel any package has spam, abuse, malware, and vulnerabilities issues, Please complaint here  https://www.npmjs.com/support

**Comment by rajaramtt** [comment]
@SorinGFS 


![image](https://user-images.githubusercontent.com/17231665/114682089-672c2400-9d2c-11eb-8929-dc2ffd1cadca.png)


If you feel any package has spam, abuse, malware, and vulnerabilities issues, Please complaint here  https://www.npmjs.com/support
