### ISSUE TITLE
Command line option "handlebars" engine support is not working

### ISSUE THREAD

**Issue by ghost** [rajathavalam/express-mvc-generator#8]
I tried to create an application with the following options:
$ express --hbs --git myapp

And it's giving me the errors below:

`   create : myapp
   create : myapp/public/js/script.js
   create : myapp/package.json
   create : myapp/app.js
   create : myapp/.gitignore
   create : myapp/public
   create : myapp/public/js
   create : myapp/config
   create : myapp/config/routes.js
   create : myapp/config/constants.js
   create : myapp/config/database.js
   create : myapp/config/passport.js
   create : myapp/config/auth.js
   create : myapp/public/img
   create : myapp/lib
   create : myapp/lib/email.js
   create : myapp/public/css
   create : myapp/public/css/style.css
   create : myapp/app/views
   create : myapp/app/views/index.hbs
   create : myapp/app/views/layout.hbs
   create : myapp/app/views/error.hbs
fs.js:667
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open 'D:\Users\dcarpioc\AppData\Roaming\npm\node_modules\express-mvc-generator\templates\common\login.ejs'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at copy_template (D:\Users\dcarpioc\AppData\Roaming\npm\node_modules\express-mvc-generator\bin\express:340:16)
    at D:\Users\dcarpioc\AppData\Roaming\npm\node_modules\express-mvc-generator\bin\express:191:11
    at D:\Users\dcarpioc\AppData\Roaming\npm\node_modules\express-mvc-generator\bin\express:459:11
    at D:\Users\dcarpioc\AppData\Roaming\npm\node_modules\express-mvc-generator\node_modules\mkdirp\index.js:30:20
    at FSReqWrap.oncomplete (fs.js:153:20)`

Please anyone can help?

**Comment by rajaramtt** [comment]
I have been a little bit busy with my development work, unable to check your issues. I am developing advanced full-featured ECMAScript based express-mvc-generator(popular template engines, popular databases, popular third-party modules, angular6, react, Profiler, Authentication, and Social media integrations ). I will update you once it has done.

Thanks for using express-mvc-generator , Happy Coding.

**Comment by ochorocho** [comment]
Getting the same when running `express myapp --css sass --git --hbs`

Log
```
fs.js:145
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/XXXX/.nvm/versions/node/v10.4.1/lib/node_modules/express-mvc-generator/templates/common/login.ejs'
    at Object.fs.openSync (fs.js:579:3)
    at Object.fs.readFileSync (fs.js:485:33)
    at copy_template (/Users/XXXX/.nvm/versions/node/v10.4.1/lib/node_modules/express-mvc-generator/bin/express:340:16)
    at /Users/XXXX/.nvm/versions/node/v10.4.1/lib/node_modules/express-mvc-generator/bin/express:191:11
    at /Users/XXXX/.nvm/versions/node/v10.4.1/lib/node_modules/express-mvc-generator/bin/express:459:11
    at /Users/XXXX/.nvm/versions/node/v10.4.1/lib/node_modules/express-mvc-generator/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:185:5)
```

**Comment by rajaramtt** [comment]
I have been a little bit busy with my development work, unable to check your issues. I am developing advanced full-featured ECMAScript based express-mvc-generator(popular template engines, popular databases, popular third-party modules, angular6, react, Profiler, Authentication, and Social media integrations ). I will update you once it has done.

Thanks for using express-mvc-generator , Happy Coding.
